"""Background agent runner — executes Claude agents independently of WebSocket connections."""

from __future__ import annotations

import asyncio
import json
import logging
import re
import subprocess
import time
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path

from claude_agent_sdk import (
    AssistantMessage,
    ClaudeAgentOptions,
    ClaudeSDKClient,
    ResultMessage,
    StreamEvent,
    SystemMessage,
    TextBlock,
    ToolResultBlock,
    ToolUseBlock,
)
from claude_agent_sdk.types import (
    PermissionResultAllow,
    PermissionResultDeny,
    ThinkingBlock,
)

from deathstar_server.errors import AppError
from deathstar_server.services.event_bus import EventBus
from deathstar_server.services.worktree import WorktreeManager
from deathstar_server.web.conversations import ConversationStore
from deathstar_shared.models import WorkflowKind

logger = logging.getLogger(__name__)


_MAX_AGENTS = 8
_AGENT_TTL_SECONDS = 15 * 60  # 15 minutes idle before eviction
_COMPLETED_RETAIN_SECONDS = 5 * 60  # keep completed agents for snapshot access
_SUBSCRIBER_QUEUE_SIZE = 512
_PERMISSION_TIMEOUT_SECONDS = 120


# ---------------------------------------------------------------------------
# Agent events — published to subscribers
# ---------------------------------------------------------------------------


class AgentEventType(str, Enum):
    STARTED = "started"
    TEXT_DELTA = "text_delta"
    THINKING_DELTA = "thinking_delta"
    TOOL_USE = "tool_use"
    TOOL_RESULT = "tool_result"
    PERMISSION_REQUEST = "permission_request"
    RESULT = "result"
    ERROR = "error"
    STATUS = "status"
    COMPACT_DONE = "compact_done"


@dataclass
class AgentEvent:
    type: AgentEventType
    data: dict = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Agent status
# ---------------------------------------------------------------------------


class AgentStatus(str, Enum):
    STARTING = "starting"
    RUNNING = "running"
    WAITING_PERMISSION = "waiting_permission"
    COMPLETED = "completed"
    FAILED = "failed"


# ---------------------------------------------------------------------------
# Shared helpers (moved from agent_ws.py)
# ---------------------------------------------------------------------------


_BRANCH_NAME_RE = re.compile(r"^[a-zA-Z0-9._/\-]+$")
_PROTECTED_BRANCHES = frozenset({"main", "master"})
_PUSH_TO_PROTECTED_RE = re.compile(
    r"git\s+push\b.*?\b(?:origin\s+)?(?:HEAD:)?("
    + "|".join(_PROTECTED_BRANCHES)
    + r")\b",
)

_CLAUDEIGNORE_CONTENT = """\
# Auto-generated by DeathStar to speed up Claude CLI startup
node_modules/
.git/objects/
.git/pack/
dist/
build/
__pycache__/
.venv/
venv/
.next/
.nuxt/
coverage/
.terraform/
*.lock
"""

_AUTH_ERROR_HINTS = (
    "auth", "unauthorized", "unauthenticated", "token", "credential",
    "login", "expired", "403", "401", "permission denied", "not logged in",
    "sign in", "api key",
)

# JSON settings string passed to ClaudeAgentOptions to disable the
# Co-Authored-By trailer that Claude Code adds to commits/PRs.
_AGENT_SETTINGS_JSON = json.dumps({"attribution": {"commit": "", "pr": ""}})


def _validate_branch_name(branch: str) -> bool:
    if not branch or len(branch) > 256:
        return False
    if branch.startswith("-") or branch.startswith("."):
        return False
    if ".." in branch or branch.endswith(".lock"):
        return False
    return bool(_BRANCH_NAME_RE.match(branch))


def _is_auth_error(error: Exception) -> bool:
    msg = str(error).lower()
    return any(hint in msg for hint in _AUTH_ERROR_HINTS)


def _check_protected_branch_push(tool_name: str, tool_input) -> PermissionResultDeny | None:
    if tool_name != "Bash":
        return None
    command = ""
    if isinstance(tool_input, dict):
        command = str(tool_input.get("command", ""))
    elif isinstance(tool_input, str):
        command = tool_input
    if not command:
        return None
    if _PUSH_TO_PROTECTED_RE.search(command):
        logger.warning("BLOCKED push to protected branch: %s", command[:200])
        return PermissionResultDeny(
            message="Pushing directly to main/master is not allowed. Create a feature branch instead.",
        )
    if re.search(r"git\s+push\s*$", command.strip()) or re.search(r"git\s+push\s+origin\s*$", command.strip()):
        logger.warning("BLOCKED ambiguous git push (could push main): %s", command[:200])
        return PermissionResultDeny(
            message="Ambiguous git push — specify a feature branch explicitly. Pushing to main/master is not allowed.",
        )
    if re.search(r"git\s+push\s+.*--force", command) or re.search(r"git\s+push\s+-f\b", command):
        logger.warning("BLOCKED force push: %s", command[:200])
        return PermissionResultDeny(message="Force push is not allowed from DeathStar.")
    return None


def _ensure_claudeignore(repo_root: Path) -> None:
    ignore_path = repo_root / ".claudeignore"
    if not ignore_path.exists():
        try:
            ignore_path.write_text(_CLAUDEIGNORE_CONTENT)
        except OSError:
            pass


def _claude_agent_env() -> dict:
    import os as _os
    from deathstar_server.app_state import settings as _settings
    from deathstar_server.services.gitops import _random_star_wars_character
    env = _os.environ.copy()
    config_dir = _settings.workspace_root / "deathstar" / ".claude"
    env["CLAUDE_CONFIG_DIR"] = str(config_dir)
    token_path = config_dir / "oauth_token"
    if token_path.is_file():
        token = token_path.read_text().strip()
        if token:
            env["CLAUDE_CODE_OAUTH_TOKEN"] = token
    character = _random_star_wars_character()
    env["GIT_AUTHOR_NAME"] = character["name"]
    env["GIT_AUTHOR_EMAIL"] = character["email"]
    env["GIT_COMMITTER_NAME"] = character["name"]
    env["GIT_COMMITTER_EMAIL"] = character["email"]
    return env


def _check_claude_auth() -> bool:
    try:
        env = _claude_agent_env()
        result = subprocess.run(
            ["claude", "auth", "status"],
            capture_output=True, text=True, timeout=5, env=env,
        )
        output = (result.stdout + result.stderr).strip()
        authenticated = result.returncode == 0 and "not" not in output.lower()
        logger.info("claude auth status: rc=%d authenticated=%s", result.returncode, authenticated)
        return authenticated
    except Exception as exc:
        logger.error("claude auth status check failed: %s", exc)
        return False


def _build_options(
    *,
    workflow: WorkflowKind,
    cwd: str,
    system_prompt: str | None = None,
    model: str | None = None,
    session_id: str | None = None,
    can_use_tool=None,
) -> ClaudeAgentOptions:
    from deathstar_server.services.agent import _MODE_CONFIGS
    cfg = _MODE_CONFIGS.get(workflow, _MODE_CONFIGS[WorkflowKind.PROMPT])
    kwargs: dict = {
        "allowed_tools": cfg["allowed_tools"],
        "permission_mode": cfg["permission_mode"],
        "cwd": cwd,
        "include_partial_messages": True,
        "env": _claude_agent_env(),
        "settings": _AGENT_SETTINGS_JSON,
        "debug_stderr": True,
    }
    max_turns = cfg.get("max_turns")
    if max_turns:
        kwargs["max_turns"] = max_turns
    if system_prompt:
        kwargs["system_prompt"] = system_prompt
    if model:
        kwargs["model"] = model
    if session_id:
        kwargs["resume"] = session_id
    if can_use_tool:
        kwargs["can_use_tool"] = can_use_tool
    return ClaudeAgentOptions(**kwargs)


def _usage_dict(usage) -> dict | None:
    if usage is None:
        return None
    if isinstance(usage, dict):
        inp = usage.get("input_tokens") or 0
        out = usage.get("output_tokens") or 0
        return {"input_tokens": inp, "output_tokens": out, "total_tokens": inp + out}
    return None


def _generate_branch_name(prompt: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", prompt.lower()).strip("-")
    slug = slug[:40] or "change"
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    return f"deathstar/{timestamp}-{slug}"


def _agent_already_opened_pr(text: str, blocks: list[dict]) -> bool:
    if re.search(r"https://github\.com/[^/]+/[^/]+/pull/\d+", text):
        return True
    for block in blocks:
        if block.get("type") == "tool_use" and block.get("tool") == "Bash":
            inp = block.get("input", "")
            if isinstance(inp, dict):
                inp = inp.get("command", "")
            if "gh pr create" in str(inp):
                return True
    return False


# ---------------------------------------------------------------------------
# RunningAgent — one per active agent execution
# ---------------------------------------------------------------------------


@dataclass
class RunningAgent:
    conversation_id: str
    repo: str
    branch: str | None
    workflow: WorkflowKind
    working_dir: Path
    client: ClaudeSDKClient
    auto_accept: bool
    status: AgentStatus = AgentStatus.STARTING
    accumulated_text: str = ""
    accumulated_blocks: list[dict] = field(default_factory=list)
    permission_future: asyncio.Future | None = None
    created_at: float = field(default_factory=time.time)
    last_active: float = field(default_factory=time.time)
    completed_at: float | None = None
    task: asyncio.Task | None = None
    compact_task: asyncio.Task | None = None
    prompt: str = ""
    # Per-subscriber bounded queues
    _subscribers: dict[str, asyncio.Queue] = field(default_factory=dict)

    def publish(self, event: AgentEvent) -> None:
        """Publish an event to all subscribers. Drop if queue full."""
        for sub_id, queue in list(self._subscribers.items()):
            try:
                queue.put_nowait(event)
            except asyncio.QueueFull:
                logger.warning("subscriber %s queue full, dropping event %s", sub_id, event.type)

    def subscribe(self) -> tuple[str, asyncio.Queue]:
        sub_id = str(uuid.uuid4())
        queue: asyncio.Queue = asyncio.Queue(maxsize=_SUBSCRIBER_QUEUE_SIZE)
        self._subscribers[sub_id] = queue
        return sub_id, queue

    def unsubscribe(self, sub_id: str) -> None:
        self._subscribers.pop(sub_id, None)

    @property
    def has_subscribers(self) -> bool:
        return bool(self._subscribers)

    def get_snapshot(self) -> dict:
        """Return current accumulated state for late-joining subscribers."""
        return {
            "status": self.status.value,
            "text": self.accumulated_text,
            "blocks": self.accumulated_blocks,
            "conversation_id": self.conversation_id,
            "repo": self.repo,
            "branch": self.branch,
            "workflow": self.workflow.value,
        }


# ---------------------------------------------------------------------------
# AgentRunner — singleton that manages all background agents
# ---------------------------------------------------------------------------


class AgentRunner:

    def __init__(
        self,
        conversation_store: ConversationStore,
        worktree_manager: WorktreeManager,
        event_bus: EventBus,
    ) -> None:
        self._conversation_store = conversation_store
        self._worktree_manager = worktree_manager
        self._event_bus = event_bus
        self._agents: dict[str, RunningAgent] = {}
        self._branch_locks: dict[tuple[str, str], str] = {}
        self._reaper_task: asyncio.Task | None = None
        self._loop: asyncio.AbstractEventLoop | None = None

    async def start(self) -> None:
        self._loop = asyncio.get_running_loop()
        self._reaper_task = asyncio.create_task(self._reaper_loop(), name="agent-reaper")
        logger.info("agent runner started")

    async def stop(self) -> None:
        if self._reaper_task:
            self._reaper_task.cancel()
            try:
                await self._reaper_task
            except asyncio.CancelledError:
                pass
        # Gracefully stop all running agents and their tasks
        for agent in list(self._agents.values()):
            for t in (agent.task, agent.compact_task):
                if t and not t.done():
                    t.cancel()
            if agent.status in (AgentStatus.RUNNING, AgentStatus.WAITING_PERMISSION, AgentStatus.STARTING):
                try:
                    await agent.client.interrupt()
                except Exception:
                    pass
                try:
                    await agent.client.disconnect()
                except Exception:
                    pass
        self._agents.clear()
        self._branch_locks.clear()
        logger.info("agent runner stopped")

    # -------------------------------------------------------------------
    # Public API
    # -------------------------------------------------------------------

    async def start_agent(
        self,
        *,
        conversation_id: str | None,
        repo: str,
        branch: str | None,
        message: str,
        workflow: WorkflowKind,
        model: str | None = None,
        system_prompt: str | None = None,
        auto_accept: bool = False,
        context_files: list[str] | None = None,
    ) -> RunningAgent:
        """Start or reuse an agent for the given conversation.

        Returns the RunningAgent. Raises AppError on validation failures.
        """
        # Validate branch
        if branch and not _validate_branch_name(branch):
            raise AppError(f"Invalid branch name: '{branch}'")

        # Check branch lock
        if branch:
            lock_key = (repo, branch)
            holder = self._branch_locks.get(lock_key)
            if holder and holder != conversation_id and holder in self._agents:
                existing = self._agents[holder]
                if existing.status in (AgentStatus.RUNNING, AgentStatus.WAITING_PERMISSION, AgentStatus.STARTING):
                    raise AppError(f"Branch '{branch}' is already in use by another session.")

        # Check max agents
        active_count = sum(
            1 for a in self._agents.values()
            if a.status in (AgentStatus.RUNNING, AgentStatus.WAITING_PERMISSION, AgentStatus.STARTING)
        )
        if active_count >= _MAX_AGENTS:
            raise AppError("Too many concurrent agent sessions.")

        # Resolve working directory
        cwd = self._worktree_manager.resolve_working_dir(repo, branch)
        _ensure_claudeignore(cwd)

        # Read pinned context files
        if context_files and system_prompt:
            file_sections: list[str] = []
            for rel_path in context_files[:20]:
                if ".." in rel_path or rel_path.startswith("/"):
                    continue
                file_path = cwd / rel_path
                if file_path.is_file():
                    try:
                        content = file_path.read_text(errors="replace")[:50_000]
                        file_sections.append(f"### {rel_path}\n```\n{content}\n```")
                    except OSError:
                        continue
            if file_sections:
                system_prompt += (
                    "\n\n## Pinned Reference Files\n"
                    "The user has pinned these files as context for this conversation:\n\n"
                    + "\n\n".join(file_sections)
                )

        # Get or create conversation
        conversation_id = self._conversation_store.get_or_create(conversation_id, repo, branch)
        self._conversation_store.add_user_message(conversation_id, message)

        # Register branch lock
        if branch:
            self._branch_locks[(repo, branch)] = conversation_id

        # Check if we can reuse an existing agent
        existing = self._agents.get(conversation_id)
        if existing and existing.status in (AgentStatus.RUNNING, AgentStatus.WAITING_PERMISSION):
            # Agent still running — cancel previous reader and send follow-up
            if existing.task and not existing.task.done():
                existing.task.cancel()
                try:
                    await existing.task
                except asyncio.CancelledError:
                    pass
            existing.last_active = time.time()
            existing.workflow = workflow
            existing.prompt = message
            await existing.client.query(message)
            existing.task = asyncio.create_task(
                self._execute_agent(existing),
                name=f"agent-{conversation_id[:8]}",
            )
            return existing

        # Tear down any completed/failed agent for this conversation
        if existing:
            self._cleanup_agent(existing)

        # Pre-flight auth check
        if not _check_claude_auth():
            if branch:
                self._branch_locks.pop((repo, branch), None)
            raise AppError("Claude is not authenticated. Open the Claude menu to connect your account.", code="AUTH_REQUIRED")

        # Look up SDK session ID for multi-turn continuity
        sdk_session_id = self._conversation_store.get_session_id(conversation_id)

        # Create the agent
        agent = RunningAgent(
            conversation_id=conversation_id,
            repo=repo,
            branch=branch,
            workflow=workflow,
            working_dir=cwd,
            client=None,  # type: ignore[arg-type] — set below
            auto_accept=auto_accept,
            prompt=message,
        )
        self._agents[conversation_id] = agent

        # Build permission callback
        async def can_use_tool(tool_name, tool_input, context):
            deny = _check_protected_branch_push(tool_name, tool_input)
            if deny:
                return deny
            if agent.auto_accept:
                logger.info("auto-accepting tool: %s", tool_name)
                return PermissionResultAllow()
            # Ask subscribers for permission
            agent.publish(AgentEvent(
                type=AgentEventType.PERMISSION_REQUEST,
                data={"tool": tool_name, "input": tool_input},
            ))
            agent.status = AgentStatus.WAITING_PERMISSION
            agent.permission_future = asyncio.get_running_loop().create_future()
            try:
                result = await asyncio.wait_for(
                    agent.permission_future,
                    timeout=_PERMISSION_TIMEOUT_SECONDS,
                )
            except asyncio.TimeoutError:
                if agent.has_subscribers:
                    return PermissionResultDeny(message="Permission request timed out")
                logger.warning("No subscriber connected — auto-accepting tool: %s", tool_name)
                return PermissionResultAllow()
            finally:
                agent.permission_future = None
                agent.status = AgentStatus.RUNNING
            return result

        options = _build_options(
            workflow=workflow,
            cwd=str(cwd),
            system_prompt=system_prompt,
            model=model,
            session_id=sdk_session_id,
            can_use_tool=can_use_tool,
        )

        logger.info("creating ClaudeSDKClient: conv=%s cwd=%s workflow=%s", conversation_id, cwd, workflow)
        client = ClaudeSDKClient(options=options)
        try:
            await client.connect()
        except Exception as exc:
            self._cleanup_agent(agent)
            error_code = "AUTH_EXPIRED" if _is_auth_error(exc) else "SDK_ERROR"
            raise AppError(
                "Claude authentication has expired." if _is_auth_error(exc)
                else f"Failed to start Claude agent: {exc}",
                code=error_code,
            ) from exc

        agent.client = client
        agent.status = AgentStatus.RUNNING

        try:
            await client.query(message)
        except Exception as exc:
            error_code = "AUTH_EXPIRED" if _is_auth_error(exc) else "SDK_ERROR"
            agent.publish(AgentEvent(
                type=AgentEventType.ERROR,
                data={"code": error_code, "message": str(exc)},
            ))
            agent.status = AgentStatus.FAILED
            raise AppError(str(exc), code=error_code) from exc

        # Notify subscribers
        agent.publish(AgentEvent(
            type=AgentEventType.STARTED,
            data={"conversation_id": conversation_id},
        ))

        # Spawn execution task
        agent.task = asyncio.create_task(
            self._execute_agent(agent),
            name=f"agent-{conversation_id[:8]}",
        )
        return agent

    def subscribe(self, conversation_id: str) -> tuple[str, asyncio.Queue] | None:
        agent = self._agents.get(conversation_id)
        if not agent:
            return None
        return agent.subscribe()

    def unsubscribe(self, conversation_id: str, sub_id: str) -> None:
        agent = self._agents.get(conversation_id)
        if agent:
            agent.unsubscribe(sub_id)

    def respond_permission(self, conversation_id: str, allow: bool) -> None:
        agent = self._agents.get(conversation_id)
        if not agent or not agent.permission_future or agent.permission_future.done():
            return
        if allow:
            agent.permission_future.set_result(PermissionResultAllow())
        else:
            agent.permission_future.set_result(
                PermissionResultDeny(message="User denied via web UI")
            )

    async def interrupt(self, conversation_id: str) -> None:
        agent = self._agents.get(conversation_id)
        if agent and agent.client:
            try:
                await agent.client.interrupt()
            except Exception:
                pass

    def interrupt_threadsafe(self, conversation_id: str) -> None:
        """Thread-safe interrupt for use from sync HTTP handlers."""
        agent = self._agents.get(conversation_id)
        if not agent or not agent.client:
            return
        if not self._loop or not self._loop.is_running():
            return
        asyncio.run_coroutine_threadsafe(agent.client.interrupt(), self._loop)

    async def send_followup(self, conversation_id: str, message: str) -> None:
        agent = self._agents.get(conversation_id)
        if not agent or agent.status not in (AgentStatus.RUNNING, AgentStatus.COMPLETED):
            raise AppError("No active agent for this conversation")
        # Cancel previous reader before starting a new turn
        if agent.task and not agent.task.done():
            agent.task.cancel()
            try:
                await agent.task
            except asyncio.CancelledError:
                pass
        agent.last_active = time.time()
        self._conversation_store.add_user_message(conversation_id, message)
        await agent.client.query(message)
        # Reset state for new turn
        agent.accumulated_text = ""
        agent.accumulated_blocks = []
        agent.status = AgentStatus.RUNNING
        agent.task = asyncio.create_task(
            self._execute_agent(agent),
            name=f"agent-{conversation_id[:8]}",
        )

    async def compact(self, conversation_id: str) -> None:
        agent = self._agents.get(conversation_id)
        if not agent or not agent.client:
            return
        agent.last_active = time.time()
        await agent.client.query("/compact")
        agent.compact_task = asyncio.create_task(self._read_compact(agent))

    def get_agent(self, conversation_id: str) -> RunningAgent | None:
        return self._agents.get(conversation_id)

    def list_active(self) -> list[RunningAgent]:
        return [
            a for a in self._agents.values()
            if a.status in (AgentStatus.RUNNING, AgentStatus.WAITING_PERMISSION, AgentStatus.STARTING)
        ]

    def get_active_branches(self) -> dict[tuple[str, str], str]:
        return dict(self._branch_locks)

    def is_branch_active(self, repo: str, branch: str) -> bool:
        holder = self._branch_locks.get((repo, branch))
        return holder is not None and holder in self._agents

    # -------------------------------------------------------------------
    # Execution loop
    # -------------------------------------------------------------------

    async def _execute_agent(self, agent: RunningAgent) -> None:
        """Read messages from the SDK client and publish events. Persists on completion."""
        started = time.perf_counter()
        accumulated_text = ""
        delta_sent_text = ""
        accumulated_blocks: list[dict] = []
        msg_count = 0

        logger.info("agent execution started: conv=%s", agent.conversation_id)

        try:
            async for message in agent.client.receive_messages():
                msg_count += 1
                agent.last_active = time.time()

                if isinstance(message, AssistantMessage):
                    for block in message.content:
                        if isinstance(block, TextBlock):
                            already_sent = (
                                block.text in delta_sent_text
                                or block.text in accumulated_text
                            )
                            if not already_sent:
                                accumulated_text += block.text
                                agent.publish(AgentEvent(
                                    type=AgentEventType.TEXT_DELTA,
                                    data={"text": block.text},
                                ))
                            elif not accumulated_text.endswith(block.text) and block.text not in accumulated_text:
                                accumulated_text += block.text
                            # Track in blocks
                            if accumulated_blocks and accumulated_blocks[-1].get("type") == "text":
                                if block.text not in accumulated_blocks[-1]["text"]:
                                    if accumulated_blocks[-1]["text"] and not accumulated_blocks[-1]["text"].endswith("\n\n"):
                                        accumulated_blocks[-1]["text"] += "\n\n"
                                    accumulated_blocks[-1]["text"] += block.text
                            else:
                                if not any(b.get("type") == "text" and block.text in b["text"] for b in accumulated_blocks):
                                    accumulated_blocks.append({"type": "text", "text": block.text})

                        elif isinstance(block, ToolUseBlock):
                            accumulated_blocks.append({
                                "type": "tool_use", "id": block.id,
                                "tool": block.name, "input": block.input,
                            })
                            agent.publish(AgentEvent(
                                type=AgentEventType.TOOL_USE,
                                data={"id": block.id, "tool": block.name, "input": block.input},
                            ))

                        elif isinstance(block, ToolResultBlock):
                            content = block.content
                            if isinstance(content, list):
                                content = "\n".join(
                                    item.get("text", str(item))
                                    for item in content
                                    if isinstance(item, dict)
                                )
                            result_str = str(content or "")
                            accumulated_blocks.append({
                                "type": "tool_result", "toolUseId": block.tool_use_id,
                                "content": result_str[:2000],
                                "isError": block.is_error or False,
                            })
                            agent.publish(AgentEvent(
                                type=AgentEventType.TOOL_RESULT,
                                data={
                                    "tool_use_id": block.tool_use_id,
                                    "content": result_str,
                                    "is_error": block.is_error or False,
                                },
                            ))

                        elif isinstance(block, ThinkingBlock):
                            if accumulated_blocks and accumulated_blocks[-1].get("type") == "thinking":
                                accumulated_blocks[-1]["text"] += block.thinking
                            else:
                                accumulated_blocks.append({"type": "thinking", "text": block.thinking})

                elif isinstance(message, StreamEvent):
                    event_data = message.event
                    event_type = event_data.get("type", "")
                    if event_type == "content_block_start":
                        cb = event_data.get("content_block", {})
                        if cb.get("type") == "text":
                            if accumulated_blocks and accumulated_blocks[-1].get("type") == "text" and accumulated_blocks[-1]["text"]:
                                sep = "\n\n"
                                accumulated_text += sep
                                delta_sent_text += sep
                                accumulated_blocks[-1]["text"] += sep
                                agent.publish(AgentEvent(
                                    type=AgentEventType.TEXT_DELTA,
                                    data={"text": sep},
                                ))
                    elif event_type == "content_block_delta":
                        delta = event_data.get("delta", {})
                        if delta.get("type") == "text_delta":
                            text = delta.get("text", "")
                            if text:
                                accumulated_text += text
                                delta_sent_text += text
                                if accumulated_blocks and accumulated_blocks[-1].get("type") == "text":
                                    accumulated_blocks[-1]["text"] += text
                                else:
                                    accumulated_blocks.append({"type": "text", "text": text})
                                agent.publish(AgentEvent(
                                    type=AgentEventType.TEXT_DELTA,
                                    data={"text": text},
                                ))
                        elif delta.get("type") == "thinking_delta":
                            text = delta.get("thinking", "")
                            if text:
                                if accumulated_blocks and accumulated_blocks[-1].get("type") == "thinking":
                                    accumulated_blocks[-1]["text"] += text
                                else:
                                    accumulated_blocks.append({"type": "thinking", "text": text})
                                agent.publish(AgentEvent(
                                    type=AgentEventType.THINKING_DELTA,
                                    data={"text": text},
                                ))

                elif isinstance(message, ResultMessage):
                    duration_ms = int((time.perf_counter() - started) * 1000)
                    final_text = accumulated_text or message.result or ""

                    logger.info(
                        "ResultMessage: session_id=%s is_error=%s turns=%s cost=$%s text_len=%d (conv=%s)",
                        message.session_id, message.is_error, message.num_turns,
                        message.total_cost_usd, len(final_text), agent.conversation_id,
                    )

                    # Handle stale sessions
                    if message.is_error and duration_ms < 5000 and (message.num_turns or 0) <= 1:
                        logger.warning(
                            "resumed session failed quickly (%dms) — clearing session_id for conv=%s",
                            duration_ms, agent.conversation_id,
                        )
                        self._conversation_store.update_session_id(agent.conversation_id, None)
                    elif message.session_id:
                        self._conversation_store.update_session_id(
                            agent.conversation_id, message.session_id,
                        )

                    # PR post-processing
                    if agent.workflow == WorkflowKind.PR and not message.is_error:
                        if _agent_already_opened_pr(accumulated_text, accumulated_blocks):
                            logger.info("agent already opened a PR — skipping post-processing")
                        else:
                            await self._post_agent_open_pr(agent, agent.prompt)

                    # Persist to DB
                    msg_id = self._conversation_store.add_assistant_message(
                        agent.conversation_id,
                        final_text,
                        workflow=agent.workflow,
                        provider="anthropic",
                        model="claude",
                        duration_ms=duration_ms,
                        agent_blocks=accumulated_blocks or None,
                    )

                    # Publish result event
                    agent.publish(AgentEvent(
                        type=AgentEventType.RESULT,
                        data={
                            "conversation_id": agent.conversation_id,
                            "message_id": msg_id,
                            "session_id": message.session_id,
                            "model": "claude",
                            "duration_ms": duration_ms,
                            "num_turns": message.num_turns,
                            "usage": _usage_dict(message.usage),
                            "cost_usd": message.total_cost_usd,
                            "content": final_text,
                            "status": "failed" if message.is_error else "succeeded",
                        },
                    ))

                    agent.status = AgentStatus.COMPLETED
                    agent.completed_at = time.time()
                    break

                elif isinstance(message, SystemMessage):
                    subtype = getattr(message, "subtype", "")
                    data = getattr(message, "data", {}) or {}
                    if subtype == "api_retry":
                        delay_ms = data.get("retry_delay_ms", 0)
                        attempt = data.get("attempt", 0)
                        max_retries = data.get("max_retries", 0)
                        delay_s = delay_ms // 1000
                        logger.warning(
                            "api_retry: attempt=%d/%d delay=%ds (conv=%s)",
                            attempt, max_retries, delay_s, agent.conversation_id,
                        )
                        agent.publish(AgentEvent(
                            type=AgentEventType.STATUS,
                            data={
                                "status": "rate_limited",
                                "message": f"Rate limited — retrying in {delay_s}s (attempt {attempt}/{max_retries})",
                                "retry_delay_s": delay_s,
                                "attempt": attempt,
                                "max_retries": max_retries,
                            },
                        ))

            # Update accumulated state on the agent for snapshot access
            agent.accumulated_text = accumulated_text
            agent.accumulated_blocks = accumulated_blocks

            if agent.status != AgentStatus.COMPLETED:
                agent.status = AgentStatus.FAILED
                agent.completed_at = time.time()

            logger.info(
                "agent execution ended: %d messages, %.1fs (conv=%s)",
                msg_count, time.perf_counter() - started, agent.conversation_id,
            )

        except Exception as exc:
            logger.exception("agent execution error after %d messages: %s", msg_count, exc)
            agent.accumulated_text = accumulated_text
            agent.accumulated_blocks = accumulated_blocks
            agent.status = AgentStatus.FAILED
            agent.completed_at = time.time()
            error_code = "AUTH_EXPIRED" if _is_auth_error(exc) else "INTERNAL_ERROR"
            error_msg = (
                "Claude authentication has expired."
                if _is_auth_error(exc)
                else str(exc)
            )
            agent.publish(AgentEvent(
                type=AgentEventType.ERROR,
                data={"code": error_code, "message": error_msg},
            ))

    async def _read_compact(self, agent: RunningAgent) -> None:
        try:
            async for message in agent.client.receive_messages():
                agent.last_active = time.time()
                if isinstance(message, ResultMessage):
                    summary = message.result or "Context compacted successfully"
                    agent.publish(AgentEvent(
                        type=AgentEventType.COMPACT_DONE,
                        data={"summary": summary},
                    ))
                    return
            agent.publish(AgentEvent(
                type=AgentEventType.COMPACT_DONE,
                data={"summary": "Context compacted"},
            ))
        except Exception as exc:
            logger.warning("compact read error: %s", exc)
            agent.publish(AgentEvent(
                type=AgentEventType.COMPACT_DONE,
                data={"summary": "Compact completed"},
            ))

    async def _post_agent_open_pr(self, agent: RunningAgent, prompt: str) -> None:
        """After a PR-workflow agent run, commit changes and open a GitHub PR."""
        from deathstar_server.app_state import git_service, github_service

        repo_root = agent.working_dir
        current = git_service.current_branch(repo_root)
        has_uncommitted = git_service.has_uncommitted_changes(repo_root)

        agent_committed = False
        if not has_uncommitted:
            try:
                result = subprocess.run(
                    ["git", "log", "origin/main..HEAD", "--oneline"],
                    cwd=str(repo_root), capture_output=True, text=True, check=True,
                )
                agent_committed = bool(result.stdout.strip())
            except subprocess.CalledProcessError:
                pass

        if not has_uncommitted and not agent_committed:
            agent.publish(AgentEvent(
                type=AgentEventType.TEXT_DELTA,
                data={"text": "\n\n*No changes detected — skipping PR creation.*"},
            ))
            return

        agent.publish(AgentEvent(
            type=AgentEventType.TEXT_DELTA,
            data={"text": "\n\n---\n*Creating pull request...*\n"},
        ))

        try:
            github_service.ensure_remote_origin(repo_root)

            if has_uncommitted:
                branch_name = _generate_branch_name(prompt)
                git_service.ensure_branch(repo_root, branch_name)
                commit_msg = f"deathstar: {prompt[:80]}"
                git_service.commit_all(repo_root, commit_msg)
                agent.publish(AgentEvent(
                    type=AgentEventType.TEXT_DELTA,
                    data={"text": f"Committed to `{branch_name}`. Pushing..."},
                ))
                github_service.push_branch(repo_root, branch_name)
            else:
                branch_name = current
                try:
                    result = subprocess.run(
                        ["git", "log", f"origin/{branch_name}..HEAD", "--oneline"],
                        cwd=str(repo_root), capture_output=True, text=True, check=True,
                    )
                    if result.stdout.strip():
                        agent.publish(AgentEvent(
                            type=AgentEventType.TEXT_DELTA,
                            data={"text": f"Pushing `{branch_name}`..."},
                        ))
                        github_service.push_branch(repo_root, branch_name)
                    else:
                        agent.publish(AgentEvent(
                            type=AgentEventType.TEXT_DELTA,
                            data={"text": f"Branch `{branch_name}` already pushed."},
                        ))
                except subprocess.CalledProcessError:
                    agent.publish(AgentEvent(
                        type=AgentEventType.TEXT_DELTA,
                        data={"text": f"Pushing `{branch_name}`..."},
                    ))
                    github_service.push_branch(repo_root, branch_name)

            agent.publish(AgentEvent(
                type=AgentEventType.TEXT_DELTA,
                data={"text": " Opening PR..."},
            ))

            base_branch = "main"
            try:
                result = subprocess.run(
                    ["git", "symbolic-ref", "refs/remotes/origin/HEAD"],
                    cwd=str(repo_root), capture_output=True, text=True, check=True,
                )
                base_branch = result.stdout.strip().rsplit("/", 1)[-1]
            except subprocess.CalledProcessError:
                pass

            pr_url = await github_service.create_pull_request(
                repo_root=repo_root,
                title=prompt[:120],
                body=f"Generated by DeathStar agent.\n\n**Prompt:** {prompt}",
                head_branch=branch_name,
                base_branch=base_branch,
                draft=False,
            )
            agent.publish(AgentEvent(
                type=AgentEventType.TEXT_DELTA,
                data={"text": f"\n\nPR opened: {pr_url}"},
            ))
            logger.info("PR created: %s (conv=%s)", pr_url, agent.conversation_id)

        except Exception as exc:
            logger.exception("post-agent PR creation failed: %s", exc)
            agent.publish(AgentEvent(
                type=AgentEventType.TEXT_DELTA,
                data={"text": f"\n\n*PR creation failed: {exc}*"},
            ))

    # -------------------------------------------------------------------
    # Cleanup
    # -------------------------------------------------------------------

    def _cleanup_agent(self, agent: RunningAgent) -> None:
        """Remove an agent and release its branch lock."""
        self._agents.pop(agent.conversation_id, None)
        if agent.branch:
            lock_key = (agent.repo, agent.branch)
            if self._branch_locks.get(lock_key) == agent.conversation_id:
                self._branch_locks.pop(lock_key, None)

    async def _reaper_loop(self) -> None:
        """Periodically clean up stale and completed agents."""
        while True:
            await asyncio.sleep(60)
            try:
                now = time.time()
                to_remove: list[str] = []
                for conv_id, agent in list(self._agents.items()):
                    if agent.status in (AgentStatus.COMPLETED, AgentStatus.FAILED):
                        if agent.completed_at and now - agent.completed_at > _COMPLETED_RETAIN_SECONDS:
                            to_remove.append(conv_id)
                    elif now - agent.last_active > _AGENT_TTL_SECONDS:
                        # Stale running agent — evict
                        logger.info("evicting stale agent: conv=%s branch=%s", conv_id, agent.branch)
                        try:
                            await agent.client.disconnect()
                        except Exception:
                            pass
                        to_remove.append(conv_id)

                for conv_id in to_remove:
                    agent = self._agents.get(conv_id)
                    if agent:
                        self._cleanup_agent(agent)
                        logger.info("reaped agent: conv=%s status=%s", conv_id, agent.status)

            except asyncio.CancelledError:
                raise
            except Exception:
                logger.warning("agent reaper error", exc_info=True)
