"""Background agent runner — executes Claude agents independently of WebSocket connections."""

from __future__ import annotations

import asyncio
import json
import logging
import os
import re
import subprocess
import time
import uuid
from collections.abc import Callable
from contextlib import AsyncExitStack
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path

import anyio
from anyio.abc import TaskGroup
from anyio.streams.memory import MemoryObjectReceiveStream, MemoryObjectSendStream

from claude_agent_sdk import (
    AssistantMessage,
    ClaudeAgentOptions,
    ClaudeSDKClient,
    ResultMessage,
    StreamEvent,
    SystemMessage,
    TextBlock,
    ToolResultBlock,
    ToolUseBlock,
)
from claude_agent_sdk.types import (
    PermissionResultAllow,
    PermissionResultDeny,
    ThinkingBlock,
)

from sqlmodel import Session

from deathstar_server.config import Settings
from deathstar_server.db.models import BranchPR
from deathstar_server.errors import AppError
from deathstar_server.services.agent import _MODE_CONFIGS
from deathstar_server.services.event_bus import (
    EVENT_LOCAL_CHECKOUT,
    EVENT_LOCAL_COMMIT,
    EVENT_PR_UPDATE,
    EVENT_PUSH,
    EVENT_REPO_DIRTY,
    EventBus,
    RepoEvent,
    SOURCE_AGENT,
)
from deathstar_server.services.tool_guardrails import GuardrailTier, classify_tool_use
from deathstar_server.services.github import GitHubService
from deathstar_server.services.gitops import GitService, _random_star_wars_character
from deathstar_server.services.worktree import WorktreeManager
from deathstar_server.web.conversations import ConversationStore
from deathstar_shared.models import ErrorCode, WorkflowKind

logger = logging.getLogger(__name__)


_MAX_AGENTS = 8
_AGENT_TTL_SECONDS = 15 * 60  # 15 minutes idle before eviction
_COMPLETED_RETAIN_SECONDS = 5 * 60  # keep completed agents for snapshot access
_SUBSCRIBER_BUFFER_SIZE = 512
_PERMISSION_TIMEOUT_SECONDS = 120


# ---------------------------------------------------------------------------
# Agent events — published to subscribers
# ---------------------------------------------------------------------------


class AgentEventType(str, Enum):
    STARTED = "started"
    TEXT_DELTA = "text_delta"
    THINKING_DELTA = "thinking_delta"
    TOOL_USE = "tool_use"
    TOOL_RESULT = "tool_result"
    PERMISSION_REQUEST = "permission_request"
    RESULT = "result"
    ERROR = "error"
    STATUS = "status"
    COMPACT_DONE = "compact_done"
    PR_CREATED = "pr_created"


@dataclass
class AgentEvent:
    type: AgentEventType
    data: dict = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Agent status
# ---------------------------------------------------------------------------


class AgentStatus(str, Enum):
    STARTING = "starting"
    RUNNING = "running"
    WAITING_PERMISSION = "waiting_permission"
    COMPLETED = "completed"
    FAILED = "failed"


# ---------------------------------------------------------------------------
# Shared helpers (moved from agent_ws.py)
# ---------------------------------------------------------------------------


_BRANCH_NAME_RE = re.compile(r"^[a-zA-Z0-9._/\-]+$")
_PROTECTED_BRANCHES = frozenset({"main", "master"})
_PUSH_TO_PROTECTED_RE = re.compile(
    r"git\s+push\b.*?\b(?:origin\s+)?(?:HEAD:)?("
    + "|".join(_PROTECTED_BRANCHES)
    + r")\b",
)

_CLAUDEIGNORE_CONTENT = """\
# Auto-generated by DeathStar to speed up Claude CLI startup
node_modules/
.git/objects/
.git/pack/
dist/
build/
__pycache__/
.venv/
venv/
.next/
.nuxt/
coverage/
.terraform/
*.lock
"""

_AUTH_ERROR_HINTS = (
    "auth", "unauthorized", "unauthenticated", "token", "credential",
    "login", "expired", "403", "401", "permission denied", "not logged in",
    "sign in", "api key",
)

# JSON settings string passed to ClaudeAgentOptions to disable the
# Co-Authored-By trailer that Claude Code adds to commits/PRs.
_AGENT_SETTINGS_JSON = json.dumps({"attribution": {"commit": "", "pr": ""}})


def _validate_branch_name(branch: str) -> bool:
    if not branch or len(branch) > 256:
        return False
    if branch.startswith("-") or branch.startswith("."):
        return False
    if ".." in branch or branch.endswith(".lock"):
        return False
    return bool(_BRANCH_NAME_RE.match(branch))


def _is_auth_error(error: Exception) -> bool:
    msg = str(error).lower()
    return any(hint in msg for hint in _AUTH_ERROR_HINTS)


def _check_protected_branch_push(tool_name: str, tool_input) -> PermissionResultDeny | None:
    if tool_name != "Bash":
        return None
    command = ""
    if isinstance(tool_input, dict):
        command = str(tool_input.get("command", ""))
    elif isinstance(tool_input, str):
        command = tool_input
    if not command:
        return None
    if _PUSH_TO_PROTECTED_RE.search(command):
        logger.warning("BLOCKED push to protected branch: %s", command[:200])
        return PermissionResultDeny(
            message="Pushing directly to main/master is not allowed. Create a feature branch instead.",
        )
    if re.search(r"git\s+push\s*$", command.strip()) or re.search(r"git\s+push\s+origin\s*$", command.strip()):
        logger.warning("BLOCKED ambiguous git push (could push main): %s", command[:200])
        return PermissionResultDeny(
            message="Ambiguous git push — specify a feature branch explicitly. Pushing to main/master is not allowed.",
        )
    if re.search(r"git\s+push\s+.*--force", command) or re.search(r"git\s+push\s+-f\b", command):
        logger.warning("BLOCKED force push: %s", command[:200])
        return PermissionResultDeny(message="Force push is not allowed from DeathStar.")
    return None


def _ensure_claudeignore(repo_root: Path) -> None:
    ignore_path = repo_root / ".claudeignore"
    if not ignore_path.exists():
        try:
            ignore_path.write_text(_CLAUDEIGNORE_CONTENT)
        except OSError:
            pass


def _claude_agent_env(settings: Settings) -> dict:
    env = os.environ.copy()
    config_dir = settings.workspace_root / "deathstar" / ".claude"
    env["CLAUDE_CONFIG_DIR"] = str(config_dir)
    token_path = config_dir / "oauth_token"
    if token_path.is_file():
        token = token_path.read_text().strip()
        if token:
            env["CLAUDE_CODE_OAUTH_TOKEN"] = token
    character = _random_star_wars_character()
    env["GIT_AUTHOR_NAME"] = character["name"]
    env["GIT_AUTHOR_EMAIL"] = character["email"]
    env["GIT_COMMITTER_NAME"] = character["name"]
    env["GIT_COMMITTER_EMAIL"] = character["email"]
    return env


def _check_claude_auth(settings: Settings) -> bool:
    try:
        env = _claude_agent_env(settings)
        result = subprocess.run(
            ["claude", "auth", "status"],
            capture_output=True, text=True, timeout=5, env=env,
        )
        output = (result.stdout + result.stderr).strip()
        authenticated = result.returncode == 0 and "not" not in output.lower()
        logger.info("claude auth status: rc=%d authenticated=%s", result.returncode, authenticated)
        return authenticated
    except Exception as exc:
        logger.error("claude auth status check failed: %s", exc)
        return False


def _build_options(
    *,
    workflow: WorkflowKind,
    cwd: str,
    env: dict | None = None,
    system_prompt: str | None = None,
    model: str | None = None,
    session_id: str | None = None,
    can_use_tool=None,
) -> ClaudeAgentOptions:
    cfg = _MODE_CONFIGS.get(workflow, _MODE_CONFIGS[WorkflowKind.PROMPT])
    kwargs: dict = {
        "allowed_tools": cfg["allowed_tools"],
        "permission_mode": cfg["permission_mode"],
        "cwd": cwd,
        "include_partial_messages": True,
        "env": env if env is not None else os.environ.copy(),
        "settings": _AGENT_SETTINGS_JSON,
        "debug_stderr": True,
    }
    max_turns = cfg.get("max_turns")
    if max_turns:
        kwargs["max_turns"] = max_turns
    if system_prompt:
        kwargs["system_prompt"] = system_prompt
    if model:
        kwargs["model"] = model
    if session_id:
        kwargs["resume"] = session_id
    if can_use_tool:
        kwargs["can_use_tool"] = can_use_tool
    return ClaudeAgentOptions(**kwargs)


def _usage_dict(usage) -> dict | None:
    if usage is None:
        return None
    if isinstance(usage, dict):
        inp = usage.get("input_tokens") or 0
        out = usage.get("output_tokens") or 0
        return {"input_tokens": inp, "output_tokens": out, "total_tokens": inp + out}
    return None


def _generate_branch_name(prompt: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", prompt.lower()).strip("-")
    slug = slug[:40] or "change"
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    return f"deathstar/{timestamp}-{slug}"


def _agent_already_opened_pr(text: str, blocks: list[dict]) -> bool:
    if re.search(r"https://github\.com/[^/]+/[^/]+/pull/\d+", text):
        return True
    for block in blocks:
        if block.get("type") == "tool_use" and block.get("tool") == "Bash":
            inp = block.get("input", "")
            if isinstance(inp, dict):
                inp = inp.get("command", "")
            if "gh pr create" in str(inp):
                return True
    return False


# ---------------------------------------------------------------------------
# RunningAgent — one per active agent execution
# ---------------------------------------------------------------------------


@dataclass
class RunningAgent:
    conversation_id: str
    repo: str
    branch: str | None
    workflow: WorkflowKind
    working_dir: Path
    client: ClaudeSDKClient
    auto_accept: bool
    headless: bool = False
    status: AgentStatus = AgentStatus.STARTING
    accumulated_text: str = ""
    accumulated_blocks: list[dict] = field(default_factory=list)
    # Permission: anyio.Event for signaling, result stored separately
    permission_event: anyio.Event | None = None
    permission_result: PermissionResultAllow | PermissionResultDeny | None = None
    created_at: float = field(default_factory=time.time)
    last_active: float = field(default_factory=time.time)
    completed_at: float | None = None
    prompt: str = ""
    # Tracked asyncio task for _execute_agent (allows cancellation on reuse)
    _execute_task: asyncio.Task | None = field(default=None, repr=False)
    # Per-subscriber anyio memory object streams (send side kept for fan-out)
    _subscribers: dict[str, MemoryObjectSendStream[AgentEvent]] = field(default_factory=dict)

    def publish(self, event: AgentEvent) -> None:
        """Publish an event to all subscribers. Drop if buffer full."""
        for sub_id, send in list(self._subscribers.items()):
            try:
                send.send_nowait(event)
            except (anyio.WouldBlock, anyio.ClosedResourceError):
                pass

    def subscribe(self) -> tuple[str, MemoryObjectReceiveStream[AgentEvent]]:
        sub_id = str(uuid.uuid4())
        send, recv = anyio.create_memory_object_stream[AgentEvent](max_buffer_size=_SUBSCRIBER_BUFFER_SIZE)
        self._subscribers[sub_id] = send
        return sub_id, recv

    def unsubscribe(self, sub_id: str) -> None:
        send = self._subscribers.pop(sub_id, None)
        if send:
            send.close()

    @property
    def has_subscribers(self) -> bool:
        return bool(self._subscribers)

    def get_snapshot(self) -> dict:
        """Return current accumulated state for late-joining subscribers."""
        return {
            "status": self.status.value,
            "text": self.accumulated_text,
            "blocks": self.accumulated_blocks,
            "conversation_id": self.conversation_id,
            "repo": self.repo,
            "branch": self.branch,
            "workflow": self.workflow.value,
        }


# ---------------------------------------------------------------------------
# AgentRunner — singleton that manages all background agents
# ---------------------------------------------------------------------------


class AgentRunner:

    def __init__(
        self,
        conversation_store: ConversationStore,
        worktree_manager: WorktreeManager,
        event_bus: EventBus,
        settings: Settings,
        git_service: GitService,
        github_service: GitHubService,
    ) -> None:
        self._conversation_store = conversation_store
        self._worktree_manager = worktree_manager
        self._event_bus = event_bus
        self._settings = settings
        self._git_service = git_service
        self._github_service = github_service
        self._agents: dict[str, RunningAgent] = {}
        self._branch_locks: dict[tuple[str, str], str] = {}
        self._exit_stack: AsyncExitStack | None = None
        self._task_group: TaskGroup | None = None
        self._loop: asyncio.AbstractEventLoop | None = None
        self._on_branch_release: Callable[[], None] | None = None

    def set_on_branch_release(self, callback: Callable[[], None]) -> None:
        """Register a callback invoked whenever a branch lock is released.

        Used by the queue worker to wake up immediately when a branch
        becomes available for processing queued items.
        """
        self._on_branch_release = callback

    async def start(self) -> None:
        self._loop = asyncio.get_running_loop()
        self._exit_stack = AsyncExitStack()
        await self._exit_stack.__aenter__()
        self._task_group = await self._exit_stack.enter_async_context(
            anyio.create_task_group()
        )
        self._task_group.start_soon(self._reaper_loop)
        logger.info("agent runner started")

    async def stop(self) -> None:
        # Interrupt all running agents so their tasks finish quickly
        for agent in list(self._agents.values()):
            if agent.status in (AgentStatus.RUNNING, AgentStatus.WAITING_PERMISSION, AgentStatus.STARTING):
                try:
                    await agent.client.interrupt()
                except Exception:
                    pass
                try:
                    await agent.client.disconnect()
                except Exception:
                    pass
        # Closing the exit stack cancels the task group and all its children
        if self._exit_stack:
            await self._exit_stack.aclose()
            self._exit_stack = None
            self._task_group = None
        self._agents.clear()
        self._branch_locks.clear()
        logger.info("agent runner stopped")

    # -------------------------------------------------------------------
    # Public API
    # -------------------------------------------------------------------

    async def start_agent(
        self,
        *,
        conversation_id: str | None,
        repo: str,
        branch: str | None,
        message: str,
        workflow: WorkflowKind,
        model: str | None = None,
        system_prompt: str | None = None,
        auto_accept: bool = False,
        headless: bool = False,
        context_files: list[str] | None = None,
    ) -> RunningAgent:
        """Start or reuse an agent for the given conversation.

        Returns the RunningAgent. Raises AppError on validation failures.
        """
        # Validate branch
        if branch and not _validate_branch_name(branch):
            raise AppError(ErrorCode.INVALID_REQUEST, f"Invalid branch name: '{branch}'")

        # Check branch lock
        if branch:
            lock_key = (repo, branch)
            holder = self._branch_locks.get(lock_key)
            if holder and holder != conversation_id and holder in self._agents:
                existing = self._agents[holder]
                if existing.status in (AgentStatus.RUNNING, AgentStatus.WAITING_PERMISSION, AgentStatus.STARTING):
                    raise AppError(ErrorCode.INVALID_REQUEST, f"Branch '{branch}' is already in use by another session.")

        # Check max agents
        active_count = sum(
            1 for a in self._agents.values()
            if a.status in (AgentStatus.RUNNING, AgentStatus.WAITING_PERMISSION, AgentStatus.STARTING)
        )
        if active_count >= _MAX_AGENTS:
            raise AppError(ErrorCode.INVALID_REQUEST, "Too many concurrent agent sessions.")

        # Resolve working directory
        cwd = self._worktree_manager.resolve_working_dir(repo, branch)
        _ensure_claudeignore(cwd)

        # Read pinned context files
        if context_files and system_prompt:
            file_sections: list[str] = []
            for rel_path in context_files[:20]:
                if ".." in rel_path or rel_path.startswith("/"):
                    continue
                file_path = cwd / rel_path
                if file_path.is_file():
                    try:
                        content = file_path.read_text(errors="replace")[:50_000]
                        file_sections.append(f"### {rel_path}\n```\n{content}\n```")
                    except OSError:
                        continue
            if file_sections:
                system_prompt += (
                    "\n\n## Pinned Reference Files\n"
                    "The user has pinned these files as context for this conversation:\n\n"
                    + "\n\n".join(file_sections)
                )

        # Set a placeholder lock immediately to prevent concurrent starts on same branch.
        # The real conversation_id will overwrite this once get_or_create() resolves.
        if branch:
            lock_key = (repo, branch)
            self._branch_locks.setdefault(lock_key, "__pending__")

        # Get or create conversation
        conversation_id = self._conversation_store.get_or_create(conversation_id, repo, branch)
        self._conversation_store.add_user_message(conversation_id, message)

        # Register branch lock (overwrites the placeholder)
        if branch:
            self._branch_locks[(repo, branch)] = conversation_id

        # Check if we can reuse an existing agent
        existing = self._agents.get(conversation_id)
        if existing and existing.status in (AgentStatus.RUNNING, AgentStatus.WAITING_PERMISSION):
            # Agent still running — send follow-up, cancel any in-flight reader first
            if existing._execute_task and not existing._execute_task.done():
                existing._execute_task.cancel()
                try:
                    await existing._execute_task
                except (asyncio.CancelledError, Exception):
                    pass
            existing._execute_task = None
            # Re-acquire branch lock: the cancelled task's finally block unconditionally
            # releases it, opening a window before the next await where a concurrent
            # start_agent call for the same branch could sneak through.
            if existing.branch:
                self._branch_locks[(existing.repo, existing.branch)] = existing.conversation_id
            existing.last_active = time.time()
            existing.workflow = workflow
            existing.prompt = message
            await existing.client.query(message)
            existing._execute_task = asyncio.get_running_loop().create_task(
                self._execute_agent(existing),
                name=f"agent-{existing.conversation_id[:8]}",
            )
            return existing

        # Tear down any completed/failed agent for this conversation
        if existing:
            self._cleanup_agent(existing)

        # Pre-flight auth check
        if not _check_claude_auth(self._settings):
            if branch:
                self._branch_locks.pop((repo, branch), None)
                self._notify_branch_release()
            raise AppError(ErrorCode.AUTH_ERROR, "Claude is not authenticated. Open the Claude menu to connect your account.")

        # Look up SDK session ID for multi-turn continuity
        sdk_session_id = self._conversation_store.get_session_id(conversation_id)

        # Create the agent
        agent = RunningAgent(
            conversation_id=conversation_id,
            repo=repo,
            branch=branch,
            workflow=workflow,
            working_dir=cwd,
            client=None,  # type: ignore[arg-type] — set below
            auto_accept=auto_accept,
            headless=headless,
            prompt=message,
        )
        self._agents[conversation_id] = agent

        # Build permission callback using anyio.Event for signaling
        async def can_use_tool(tool_name, tool_input, context):
            # Legacy belt-and-suspenders check for git push to protected branches
            deny = _check_protected_branch_push(tool_name, tool_input)
            if deny:
                return deny

            # ── Tiered guardrail classification ──────────────────────
            verdict = classify_tool_use(tool_name, tool_input)

            if verdict.tier == GuardrailTier.HARD_DENY:
                rule = verdict.rule
                assert rule is not None  # always set for non-AUTO_ACCEPT
                logger.warning(
                    "GUARDRAIL HARD_DENY [%s]: %s | %s",
                    rule.category, rule.reason, verdict.command_preview,
                )
                return PermissionResultDeny(
                    message=f"Blocked: {rule.reason}. This action is never allowed from an agent.",
                )

            if verdict.tier == GuardrailTier.REQUIRE_APPROVAL:
                rule = verdict.rule
                assert rule is not None
                logger.warning(
                    "GUARDRAIL REQUIRE_APPROVAL [%s]: %s | %s",
                    rule.category, rule.reason, verdict.command_preview,
                )
                if agent.headless:
                    # Queue-worker / headless — no human to approve.
                    # Uses the explicit `headless` flag rather than checking
                    # subscriber presence so the guard still fires even when
                    # the queue worker holds a subscriber stream for reading
                    # RESULT/ERROR events.
                    logger.warning(
                        "GUARDRAIL DENIED (headless) [%s]: %s",
                        rule.category, rule.reason,
                    )
                    return PermissionResultDeny(
                        message=(
                            f"Requires approval: {rule.reason}. "
                            "Destructive actions cannot be auto-approved in queue mode — "
                            "run interactively to approve."
                        ),
                    )
                # Escalate to user — even in auto_accept mode
                return await _ask_subscriber(agent, tool_name, tool_input, guardrail={
                    "tier": verdict.tier.value,
                    "category": rule.category,
                    "reason": rule.reason,
                })

            # ── AUTO_ACCEPT tier ─────────────────────────────────────
            if agent.auto_accept:
                logger.info("auto-accepting tool: %s", tool_name)
                return PermissionResultAllow()

            # Not auto_accept — ask the subscriber (default interactive flow)
            return await _ask_subscriber(agent, tool_name, tool_input)

        async def _ask_subscriber(
            agent: RunningAgent,
            tool_name: str,
            tool_input,
            guardrail: dict | None = None,
        ):
            """Publish a permission request and wait for the subscriber's response."""
            event_data: dict = {"tool": tool_name, "input": tool_input}
            if guardrail:
                event_data["guardrail"] = guardrail
            agent.publish(AgentEvent(
                type=AgentEventType.PERMISSION_REQUEST,
                data=event_data,
            ))
            agent.status = AgentStatus.WAITING_PERMISSION
            agent.permission_event = anyio.Event()
            agent.permission_result = None
            try:
                with anyio.fail_after(_PERMISSION_TIMEOUT_SECONDS):
                    await agent.permission_event.wait()
            except TimeoutError:
                if agent.has_subscribers:
                    return PermissionResultDeny(message="Permission request timed out")
                logger.warning("No subscriber connected — auto-accepting tool: %s", tool_name)
                return PermissionResultAllow()
            finally:
                agent.permission_event = None
                agent.status = AgentStatus.RUNNING
            return agent.permission_result or PermissionResultAllow()

        options = _build_options(
            workflow=workflow,
            cwd=str(cwd),
            env=_claude_agent_env(self._settings),
            system_prompt=system_prompt,
            model=model,
            session_id=sdk_session_id,
            can_use_tool=can_use_tool,
        )

        logger.info("creating ClaudeSDKClient: conv=%s cwd=%s workflow=%s", conversation_id, cwd, workflow)
        client = ClaudeSDKClient(options=options)
        try:
            await client.connect()
        except Exception as exc:
            self._cleanup_agent(agent)
            is_auth = _is_auth_error(exc)
            raise AppError(
                ErrorCode.AUTH_ERROR if is_auth else ErrorCode.INTERNAL_ERROR,
                "Claude authentication has expired." if is_auth
                else f"Failed to start Claude agent: {exc}",
            ) from exc

        agent.client = client
        agent.status = AgentStatus.RUNNING

        try:
            await client.query(message)
        except Exception as exc:
            is_auth = _is_auth_error(exc)
            err_code_str = "AUTH_EXPIRED" if is_auth else "SDK_ERROR"
            agent.publish(AgentEvent(
                type=AgentEventType.ERROR,
                data={"code": err_code_str, "message": str(exc)},
            ))
            agent.status = AgentStatus.FAILED
            raise AppError(
                ErrorCode.AUTH_ERROR if is_auth else ErrorCode.INTERNAL_ERROR,
                str(exc),
            ) from exc

        # Notify subscribers
        agent.publish(AgentEvent(
            type=AgentEventType.STARTED,
            data={"conversation_id": conversation_id},
        ))

        # Spawn execution task — tracked for cancellation on reuse
        agent._execute_task = asyncio.get_running_loop().create_task(
            self._execute_agent(agent),
            name=f"agent-{conversation_id[:8]}",
        )
        return agent

    def subscribe(self, conversation_id: str) -> tuple[str, MemoryObjectReceiveStream[AgentEvent]] | None:
        agent = self._agents.get(conversation_id)
        if not agent:
            return None
        return agent.subscribe()

    def unsubscribe(self, conversation_id: str, sub_id: str) -> None:
        agent = self._agents.get(conversation_id)
        if agent:
            agent.unsubscribe(sub_id)

    def respond_permission(self, conversation_id: str, allow: bool) -> None:
        agent = self._agents.get(conversation_id)
        if not agent or not agent.permission_event:
            return
        if allow:
            agent.permission_result = PermissionResultAllow()
        else:
            agent.permission_result = PermissionResultDeny(message="User denied via web UI")
        agent.permission_event.set()

    async def interrupt(self, conversation_id: str) -> None:
        agent = self._agents.get(conversation_id)
        if agent and agent.client:
            try:
                await agent.client.interrupt()
            except Exception:
                pass

    def interrupt_threadsafe(self, conversation_id: str) -> None:
        """Thread-safe interrupt for use from sync HTTP handlers."""
        agent = self._agents.get(conversation_id)
        if not agent or not agent.client:
            return
        if not self._loop or not self._loop.is_running():
            return
        asyncio.run_coroutine_threadsafe(agent.client.interrupt(), self._loop)

    async def send_followup(self, conversation_id: str, message: str) -> None:
        agent = self._agents.get(conversation_id)
        if not agent or agent.status not in (AgentStatus.RUNNING, AgentStatus.COMPLETED):
            raise AppError(ErrorCode.INVALID_REQUEST, "No active agent for this conversation")
        agent.last_active = time.time()
        self._conversation_store.add_user_message(conversation_id, message)
        # Cancel any in-flight reader task before starting a new one
        if agent._execute_task and not agent._execute_task.done():
            agent._execute_task.cancel()
            try:
                await agent._execute_task
            except (asyncio.CancelledError, Exception):
                pass
        agent._execute_task = None
        # Re-acquire branch lock: the cancelled task's finally block releases it,
        # opening a yield-point window before query() where another start_agent could
        # claim the branch.
        if agent.branch:
            self._branch_locks[(agent.repo, agent.branch)] = agent.conversation_id
        # Reconnect the SDK client for multi-turn continuity if agent has completed
        if agent.status == AgentStatus.COMPLETED:
            try:
                await agent.client.connect()
            except Exception as exc:
                is_auth = _is_auth_error(exc)
                raise AppError(
                    ErrorCode.AUTH_ERROR if is_auth else ErrorCode.INTERNAL_ERROR,
                    "Claude authentication has expired." if is_auth
                    else f"Failed to reconnect agent: {exc}",
                ) from exc
        await agent.client.query(message)
        # Reset state for new turn
        agent.accumulated_text = ""
        agent.accumulated_blocks = []
        agent.status = AgentStatus.RUNNING
        # Spawn tracked execution task
        agent._execute_task = asyncio.get_running_loop().create_task(
            self._execute_agent(agent),
            name=f"agent-{conversation_id[:8]}",
        )

    async def compact(self, conversation_id: str) -> None:
        agent = self._agents.get(conversation_id)
        if not agent or not agent.client:
            return
        agent.last_active = time.time()
        await agent.client.query("/compact")
        # Task group owns the compact reader — auto-cancelled on shutdown
        self._task_group.start_soon(self._read_compact, agent)

    def get_agent(self, conversation_id: str) -> RunningAgent | None:
        return self._agents.get(conversation_id)

    def list_active(self) -> list[RunningAgent]:
        return [
            a for a in self._agents.values()
            if a.status in (AgentStatus.RUNNING, AgentStatus.WAITING_PERMISSION, AgentStatus.STARTING)
        ]

    def get_active_branches(self) -> dict[tuple[str, str], str]:
        return dict(self._branch_locks)

    def _notify_branch_release(self) -> None:
        """Fire the on_branch_release callback (e.g. to wake the queue worker)."""
        if self._on_branch_release:
            self._on_branch_release()

    def is_branch_active(self, repo: str, branch: str) -> bool:
        holder = self._branch_locks.get((repo, branch))
        return holder is not None and holder in self._agents

    # -------------------------------------------------------------------
    # Execution loop
    # -------------------------------------------------------------------

    async def _execute_agent(self, agent: RunningAgent) -> None:
        """Read messages from the SDK client and publish events. Persists on completion."""
        started = time.perf_counter()
        accumulated_text = ""
        delta_sent_text = ""
        accumulated_blocks: list[dict] = []
        msg_count = 0
        # Track tool_use_id → (tool_name, tool_input) for repo event detection
        pending_tool_uses: dict[str, tuple[str, dict | str]] = {}

        logger.info("agent execution started: conv=%s", agent.conversation_id)

        try:
            async for message in agent.client.receive_messages():
                msg_count += 1
                agent.last_active = time.time()

                if isinstance(message, AssistantMessage):
                    for block in message.content:
                        if isinstance(block, TextBlock):
                            already_sent = (
                                block.text in delta_sent_text
                                or block.text in accumulated_text
                            )
                            if not already_sent:
                                accumulated_text += block.text
                                agent.publish(AgentEvent(
                                    type=AgentEventType.TEXT_DELTA,
                                    data={"text": block.text},
                                ))
                            elif not accumulated_text.endswith(block.text) and block.text not in accumulated_text:
                                accumulated_text += block.text
                            # Track in blocks
                            if accumulated_blocks and accumulated_blocks[-1].get("type") == "text":
                                if block.text not in accumulated_blocks[-1]["text"]:
                                    if accumulated_blocks[-1]["text"] and not accumulated_blocks[-1]["text"].endswith("\n\n"):
                                        accumulated_blocks[-1]["text"] += "\n\n"
                                    accumulated_blocks[-1]["text"] += block.text
                            else:
                                if not any(b.get("type") == "text" and block.text in b["text"] for b in accumulated_blocks):
                                    accumulated_blocks.append({"type": "text", "text": block.text})

                        elif isinstance(block, ToolUseBlock):
                            accumulated_blocks.append({
                                "type": "tool_use", "id": block.id,
                                "tool": block.name, "input": block.input,
                            })
                            agent.publish(AgentEvent(
                                type=AgentEventType.TOOL_USE,
                                data={"id": block.id, "tool": block.name, "input": block.input},
                            ))
                            # Track for repo event detection on result
                            pending_tool_uses[block.id] = (block.name, block.input)

                        elif isinstance(block, ToolResultBlock):
                            content = block.content
                            if isinstance(content, list):
                                content = "\n".join(
                                    item.get("text", str(item))
                                    for item in content
                                    if isinstance(item, dict)
                                )
                            result_str = str(content or "")
                            accumulated_blocks.append({
                                "type": "tool_result", "toolUseId": block.tool_use_id,
                                "content": result_str[:2000],
                                "isError": block.is_error or False,
                            })
                            agent.publish(AgentEvent(
                                type=AgentEventType.TOOL_RESULT,
                                data={
                                    "tool_use_id": block.tool_use_id,
                                    "content": result_str,
                                    "is_error": block.is_error or False,
                                },
                            ))
                            # Detect state-changing ops → emit RepoEvents
                            tool_info = pending_tool_uses.pop(block.tool_use_id, None)
                            if tool_info:
                                self._emit_repo_events_for_tool(
                                    agent, tool_info[0], tool_info[1],
                                    result_str, block.is_error or False,
                                )

                        elif isinstance(block, ThinkingBlock):
                            if accumulated_blocks and accumulated_blocks[-1].get("type") == "thinking":
                                accumulated_blocks[-1]["text"] += block.thinking
                            else:
                                accumulated_blocks.append({"type": "thinking", "text": block.thinking})

                elif isinstance(message, StreamEvent):
                    event_data = message.event
                    event_type = event_data.get("type", "")
                    if event_type == "content_block_start":
                        cb = event_data.get("content_block", {})
                        if cb.get("type") == "text":
                            if accumulated_blocks and accumulated_blocks[-1].get("type") == "text" and accumulated_blocks[-1]["text"]:
                                sep = "\n\n"
                                accumulated_text += sep
                                delta_sent_text += sep
                                accumulated_blocks[-1]["text"] += sep
                                agent.publish(AgentEvent(
                                    type=AgentEventType.TEXT_DELTA,
                                    data={"text": sep},
                                ))
                    elif event_type == "content_block_delta":
                        delta = event_data.get("delta", {})
                        if delta.get("type") == "text_delta":
                            text = delta.get("text", "")
                            if text:
                                accumulated_text += text
                                delta_sent_text += text
                                if accumulated_blocks and accumulated_blocks[-1].get("type") == "text":
                                    accumulated_blocks[-1]["text"] += text
                                else:
                                    accumulated_blocks.append({"type": "text", "text": text})
                                agent.publish(AgentEvent(
                                    type=AgentEventType.TEXT_DELTA,
                                    data={"text": text},
                                ))
                        elif delta.get("type") == "thinking_delta":
                            text = delta.get("thinking", "")
                            if text:
                                if accumulated_blocks and accumulated_blocks[-1].get("type") == "thinking":
                                    accumulated_blocks[-1]["text"] += text
                                else:
                                    accumulated_blocks.append({"type": "thinking", "text": text})
                                agent.publish(AgentEvent(
                                    type=AgentEventType.THINKING_DELTA,
                                    data={"text": text},
                                ))

                elif isinstance(message, ResultMessage):
                    duration_ms = int((time.perf_counter() - started) * 1000)
                    final_text = accumulated_text or message.result or ""

                    logger.info(
                        "ResultMessage: session_id=%s is_error=%s turns=%s cost=$%s text_len=%d (conv=%s)",
                        message.session_id, message.is_error, message.num_turns,
                        message.total_cost_usd, len(final_text), agent.conversation_id,
                    )

                    # Handle stale sessions
                    if message.is_error and duration_ms < 5000 and (message.num_turns or 0) <= 1:
                        logger.warning(
                            "resumed session failed quickly (%dms) — clearing session_id for conv=%s",
                            duration_ms, agent.conversation_id,
                        )
                        self._conversation_store.update_session_id(agent.conversation_id, None)
                    elif message.session_id:
                        self._conversation_store.update_session_id(
                            agent.conversation_id, message.session_id,
                        )

                    # PR post-processing
                    if agent.workflow == WorkflowKind.PR and not message.is_error:
                        if _agent_already_opened_pr(accumulated_text, accumulated_blocks):
                            logger.info("agent already opened a PR — skipping post-processing")
                        else:
                            await self._post_agent_open_pr(agent, agent.prompt)

                    # Persist to DB
                    msg_id = self._conversation_store.add_assistant_message(
                        agent.conversation_id,
                        final_text,
                        workflow=agent.workflow,
                        provider="anthropic",
                        model="claude",
                        duration_ms=duration_ms,
                        agent_blocks=accumulated_blocks or None,
                    )

                    # Publish result event
                    agent.publish(AgentEvent(
                        type=AgentEventType.RESULT,
                        data={
                            "conversation_id": agent.conversation_id,
                            "message_id": msg_id,
                            "session_id": message.session_id,
                            "model": "claude",
                            "duration_ms": duration_ms,
                            "num_turns": message.num_turns,
                            "usage": _usage_dict(message.usage),
                            "cost_usd": message.total_cost_usd,
                            "content": final_text,
                            "status": "failed" if message.is_error else "succeeded",
                        },
                    ))

                    agent.status = AgentStatus.COMPLETED
                    agent.completed_at = time.time()
                    break

                elif isinstance(message, SystemMessage):
                    subtype = getattr(message, "subtype", "")
                    data = getattr(message, "data", {}) or {}
                    if subtype == "api_retry":
                        delay_ms = data.get("retry_delay_ms", 0)
                        attempt = data.get("attempt", 0)
                        max_retries = data.get("max_retries", 0)
                        delay_s = delay_ms // 1000
                        logger.warning(
                            "api_retry: attempt=%d/%d delay=%ds (conv=%s)",
                            attempt, max_retries, delay_s, agent.conversation_id,
                        )
                        agent.publish(AgentEvent(
                            type=AgentEventType.STATUS,
                            data={
                                "status": "rate_limited",
                                "message": f"Rate limited — retrying in {delay_s}s (attempt {attempt}/{max_retries})",
                                "retry_delay_s": delay_s,
                                "attempt": attempt,
                                "max_retries": max_retries,
                            },
                        ))

                # Sync incremental state to agent after every message so that
                # get_snapshot() reflects current output for reconnecting clients.
                agent.accumulated_text = accumulated_text
                agent.accumulated_blocks = accumulated_blocks

            # Final sync (redundant but safe — covers the ResultMessage break path
            # and ensures consistency if the loop exits without a ResultMessage)
            agent.accumulated_text = accumulated_text
            agent.accumulated_blocks = accumulated_blocks

            if agent.status != AgentStatus.COMPLETED:
                agent.status = AgentStatus.FAILED
                agent.completed_at = time.time()
                # Publish ERROR so queue worker (and any other subscriber)
                # unblocks — without this the recv_stream stays open and
                # the queue worker would hang waiting for RESULT/ERROR.
                agent.publish(AgentEvent(
                    type=AgentEventType.ERROR,
                    data={
                        "code": "AGENT_INCOMPLETE",
                        "message": "Agent finished without producing a result",
                    },
                ))

            logger.info(
                "agent execution ended: %d messages, %.1fs (conv=%s)",
                msg_count, time.perf_counter() - started, agent.conversation_id,
            )

        except Exception as exc:
            logger.exception("agent execution error after %d messages: %s", msg_count, exc)
            agent.accumulated_text = accumulated_text
            agent.accumulated_blocks = accumulated_blocks
            agent.status = AgentStatus.FAILED
            agent.completed_at = time.time()
            error_code = "AUTH_EXPIRED" if _is_auth_error(exc) else "INTERNAL_ERROR"
            error_msg = (
                "Claude authentication has expired."
                if _is_auth_error(exc)
                else str(exc)
            )
            agent.publish(AgentEvent(
                type=AgentEventType.ERROR,
                data={"code": error_code, "message": error_msg},
            ))

        finally:
            # Always release branch lock on completion/failure and clear tracked task
            released = False
            if agent.branch:
                lock_key = (agent.repo, agent.branch)
                if self._branch_locks.get(lock_key) == agent.conversation_id:
                    self._branch_locks.pop(lock_key, None)
                    released = True
            agent._execute_task = None
            if released:
                self._notify_branch_release()

    async def _read_compact(self, agent: RunningAgent) -> None:
        try:
            async for message in agent.client.receive_messages():
                agent.last_active = time.time()
                if isinstance(message, ResultMessage):
                    summary = message.result or "Context compacted successfully"
                    agent.publish(AgentEvent(
                        type=AgentEventType.COMPACT_DONE,
                        data={"summary": summary},
                    ))
                    return
            agent.publish(AgentEvent(
                type=AgentEventType.COMPACT_DONE,
                data={"summary": "Context compacted"},
            ))
        except Exception as exc:
            logger.warning("compact read error: %s", exc)
            agent.publish(AgentEvent(
                type=AgentEventType.COMPACT_DONE,
                data={"summary": "Compact completed"},
            ))

    async def _post_agent_open_pr(self, agent: RunningAgent, prompt: str) -> None:
        """After a PR-workflow agent run, commit changes and open a GitHub PR."""
        repo_root = agent.working_dir
        current = self._git_service.current_branch(repo_root)
        has_uncommitted = self._git_service.has_uncommitted_changes(repo_root)

        # Detect the default remote branch once; reuse throughout this method
        default_branch = "main"
        try:
            sym_result = subprocess.run(
                ["git", "symbolic-ref", "refs/remotes/origin/HEAD"],
                cwd=str(repo_root), capture_output=True, text=True, check=True,
            )
            default_branch = sym_result.stdout.strip().rsplit("/", 1)[-1]
        except subprocess.CalledProcessError:
            pass

        agent_committed = False
        if not has_uncommitted:
            try:
                result = subprocess.run(
                    ["git", "log", f"origin/{default_branch}..HEAD", "--oneline"],
                    cwd=str(repo_root), capture_output=True, text=True, check=True,
                )
                agent_committed = bool(result.stdout.strip())
            except subprocess.CalledProcessError:
                pass

        if not has_uncommitted and not agent_committed:
            agent.publish(AgentEvent(
                type=AgentEventType.TEXT_DELTA,
                data={"text": "\n\n*No changes detected — skipping PR creation.*"},
            ))
            return

        agent.publish(AgentEvent(
            type=AgentEventType.TEXT_DELTA,
            data={"text": "\n\n---\n*Creating pull request...*\n"},
        ))

        try:
            self._github_service.ensure_remote_origin(repo_root)

            if has_uncommitted:
                branch_name = _generate_branch_name(prompt)
                self._git_service.ensure_branch(repo_root, branch_name)
                commit_msg = f"deathstar: {prompt[:80]}"
                self._git_service.commit_all(repo_root, commit_msg)
                agent.publish(AgentEvent(
                    type=AgentEventType.TEXT_DELTA,
                    data={"text": f"Committed to `{branch_name}`. Pushing..."},
                ))
                self._github_service.push_branch(repo_root, branch_name)
            else:
                branch_name = current
                try:
                    result = subprocess.run(
                        ["git", "log", f"origin/{branch_name}..HEAD", "--oneline"],
                        cwd=str(repo_root), capture_output=True, text=True, check=True,
                    )
                    if result.stdout.strip():
                        agent.publish(AgentEvent(
                            type=AgentEventType.TEXT_DELTA,
                            data={"text": f"Pushing `{branch_name}`..."},
                        ))
                        self._github_service.push_branch(repo_root, branch_name)
                    else:
                        agent.publish(AgentEvent(
                            type=AgentEventType.TEXT_DELTA,
                            data={"text": f"Branch `{branch_name}` already pushed."},
                        ))
                except subprocess.CalledProcessError:
                    agent.publish(AgentEvent(
                        type=AgentEventType.TEXT_DELTA,
                        data={"text": f"Pushing `{branch_name}`..."},
                    ))
                    self._github_service.push_branch(repo_root, branch_name)

            agent.publish(AgentEvent(
                type=AgentEventType.TEXT_DELTA,
                data={"text": " Opening PR..."},
            ))

            # Reuse the default_branch already detected above (no second git symbolic-ref call)
            base_branch = default_branch

            pr_data = await self._github_service.create_pull_request(
                repo_root=repo_root,
                title=prompt[:120],
                body=f"Generated by DeathStar agent.\n\n**Prompt:** {prompt}",
                head_branch=branch_name,
                base_branch=base_branch,
                draft=False,
            )
            pr_url = pr_data["url"]
            agent.publish(AgentEvent(
                type=AgentEventType.TEXT_DELTA,
                data={"text": f"\n\nPR opened: {pr_url}"},
            ))
            logger.info("PR created: %s (conv=%s)", pr_url, agent.conversation_id)

            # Cache BranchPR immediately so it persists across refreshes
            try:
                from deathstar_server.app_state import engine as db_engine

                with Session(db_engine) as session:
                    session.merge(BranchPR(
                        repo=agent.repo,
                        branch=branch_name,
                        pr_number=pr_data["number"],
                        pr_url=pr_url,
                        pr_title=pr_data["title"],
                        pr_state=pr_data["state"],
                        draft=pr_data["draft"],
                        user=pr_data["user"],
                        base_branch=pr_data["base_branch"],
                        additions=pr_data.get("additions"),
                        deletions=pr_data.get("deletions"),
                        changed_files=pr_data.get("changed_files"),
                    ))
                    session.commit()
            except Exception:
                logger.warning("Failed to cache BranchPR after PR creation", exc_info=True)

            # Emit structured event so frontend gets PR data
            agent.publish(AgentEvent(
                type=AgentEventType.PR_CREATED,
                data={
                    "pr_url": pr_url,
                    "pr_number": pr_data["number"],
                    "pr_title": pr_data["title"],
                    "branch": branch_name,
                    "base_branch": pr_data["base_branch"],
                    "draft": pr_data["draft"],
                    "user": pr_data.get("user", ""),
                },
            ))

        except Exception as exc:
            logger.exception("post-agent PR creation failed: %s", exc)
            agent.publish(AgentEvent(
                type=AgentEventType.TEXT_DELTA,
                data={"text": f"\n\n*PR creation failed: {exc}*"},
            ))

    # -------------------------------------------------------------------
    # Agent → RepoEvent bridge
    # -------------------------------------------------------------------

    # Patterns for detecting git state changes from Bash tool results.
    # Only compiled once (class-level).
    _RE_GIT_COMMIT = re.compile(r"\bgit\s+(?:commit|merge)\b")
    _RE_GIT_PUSH = re.compile(r"\bgit\s+push\b")
    _RE_GIT_CHECKOUT = re.compile(r"\bgit\s+(?:checkout|switch)\b")
    _RE_GIT_CHECKOUT_BRANCH = re.compile(
        r"\bgit\s+(?:checkout|switch)\s+(?:-[bBcC]\s+)?([^\s;&|]+)",
    )
    _RE_GH_PR_CREATE = re.compile(r"\bgh\s+pr\s+create\b")
    _RE_GH_PR_MUTATE = re.compile(r"\bgh\s+pr\s+(?:merge|close|edit|review)\b")
    _RE_PR_NUMBER = re.compile(r"(?:^|/)(\d+)\s*$|pull/(\d+)")

    def _emit_repo_events_for_tool(
        self,
        agent: RunningAgent,
        tool_name: str,
        tool_input: dict | str,
        result: str,
        is_error: bool,
    ) -> None:
        """Detect state-changing operations from a completed tool call and emit RepoEvents.

        This bridges the gap between agent tool executions and UI state
        refreshes — the frontend subscribes to the event bus and refreshes
        commits, PRs, branches, etc. immediately rather than waiting for
        GitHub webhooks or polling.
        """
        if is_error:
            return

        if tool_name == "Bash":
            command = ""
            if isinstance(tool_input, dict):
                command = str(tool_input.get("command", ""))
            elif isinstance(tool_input, str):
                command = tool_input
            if not command:
                return

            # Git commit / merge → refresh commits + context
            if self._RE_GIT_COMMIT.search(command):
                self._event_bus.publish(RepoEvent(
                    event_type=EVENT_LOCAL_COMMIT,
                    repo=agent.repo,
                    source=SOURCE_AGENT,
                    data={"command": command[:200]},
                ))

            # Git push → refresh commits + context (same-branch = silent)
            if self._RE_GIT_PUSH.search(command):
                branch = agent.branch or "unknown"
                self._event_bus.publish(RepoEvent(
                    event_type=EVENT_PUSH,
                    repo=agent.repo,
                    source=SOURCE_AGENT,
                    data={
                        "ref": f"refs/heads/{branch}",
                        "sender": "Agent",
                    },
                ))

            # Git checkout / switch → refresh context + branches
            if self._RE_GIT_CHECKOUT.search(command):
                match = self._RE_GIT_CHECKOUT_BRANCH.search(command)
                to_branch = match.group(1) if match else "unknown"
                # Strip leading flags like -- from the branch name
                if to_branch.startswith("-"):
                    to_branch = "unknown"
                self._event_bus.publish(RepoEvent(
                    event_type=EVENT_LOCAL_CHECKOUT,
                    repo=agent.repo,
                    source=SOURCE_AGENT,
                    data={
                        "from_branch": agent.branch or "unknown",
                        "to_branch": to_branch,
                    },
                ))

            # gh pr create → refresh PRs
            if self._RE_GH_PR_CREATE.search(command):
                pr_data: dict = {"action": "created"}
                # Try to extract PR number from result output
                pr_match = self._RE_PR_NUMBER.search(result.strip())
                if pr_match:
                    pr_num = pr_match.group(1) or pr_match.group(2)
                    pr_data["number"] = int(pr_num)
                self._event_bus.publish(RepoEvent(
                    event_type=EVENT_PR_UPDATE,
                    repo=agent.repo,
                    source=SOURCE_AGENT,
                    data=pr_data,
                ))

            # gh pr merge/close/edit/review → refresh PRs
            if self._RE_GH_PR_MUTATE.search(command):
                self._event_bus.publish(RepoEvent(
                    event_type=EVENT_PR_UPDATE,
                    repo=agent.repo,
                    source=SOURCE_AGENT,
                    data={"action": "updated"},
                ))

        elif tool_name in ("Write", "Edit"):
            # File modifications → mark repo dirty so UI refreshes file tree
            self._event_bus.publish(RepoEvent(
                event_type=EVENT_REPO_DIRTY,
                repo=agent.repo,
                source=SOURCE_AGENT,
                data={"tool": tool_name},
            ))

    # -------------------------------------------------------------------
    # Cleanup
    # -------------------------------------------------------------------

    def _cleanup_agent(self, agent: RunningAgent) -> None:
        """Remove an agent and release its branch lock."""
        self._agents.pop(agent.conversation_id, None)
        released = False
        if agent.branch:
            lock_key = (agent.repo, agent.branch)
            if self._branch_locks.get(lock_key) == agent.conversation_id:
                self._branch_locks.pop(lock_key, None)
                released = True
        if released:
            self._notify_branch_release()

    async def _reaper_loop(self) -> None:
        """Periodically clean up stale and completed agents."""
        while True:
            await anyio.sleep(60)
            try:
                now = time.time()
                to_remove: list[str] = []
                for conv_id, agent in list(self._agents.items()):
                    if agent.status in (AgentStatus.COMPLETED, AgentStatus.FAILED):
                        if agent.completed_at and now - agent.completed_at > _COMPLETED_RETAIN_SECONDS:
                            to_remove.append(conv_id)
                    elif now - agent.last_active > _AGENT_TTL_SECONDS:
                        # Stale running agent — evict
                        logger.info("evicting stale agent: conv=%s branch=%s", conv_id, agent.branch)
                        try:
                            await agent.client.interrupt()
                        except Exception:
                            pass
                        try:
                            await agent.client.disconnect()
                        except Exception:
                            pass
                        to_remove.append(conv_id)

                for conv_id in to_remove:
                    agent = self._agents.get(conv_id)
                    if agent:
                        self._cleanup_agent(agent)
                        logger.info("reaped agent: conv=%s status=%s", conv_id, agent.status)

            except Exception:
                logger.warning("agent reaper error", exc_info=True)
